language: python
python:
  - "3.5"

env:
 - PYRAMID_TEST_DB_STRING=sqlite://

install:
 - pip install -e .
 - pip install --upgrade pytest

script: py.test
cache:
  directories:
    -passlib

services:
  -sqllite
